spring:
  data:
    mongodb:
      uri: mongodb+srv://${BD_USER:brunocesarduran}:${BD_PASSWORD:passadmin}@cluster0.82ztiwc.mongodb.net/${DB_NAME:webflux-course}?retryWrites=true&w=majority
      auto-index-creation: true
  application:
    name: webflux-course
